# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3600031d168dabdc8d64478f872388277e9bd06961a5d7c710be8e25ce8a2303db76dab95512a31d9578ff9aa7460edb357d27d50c3067792e8fc89d5b63090

test:
  secret_key_base: 4513aa4be9d3a19d350003221bbd67f523608bcf06b77b1ecca8d9666837ab4628cdd5dbadf96b6c3c28cd22163094302c5247bdbf6dee71dbb3cef777126ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
